/* This is a dictionary of the language defined functions
**/
export default {
  main_function: "main",
  $read: "read",
  $write: "write",
  $numElements: "total_of_elements",
  $matrixLines: "total_of_lines",
  $matrixColumns: "total_of_columns",
  $substring: "substring",
  $length: "length",
  $uppercase: "uppercase",
  $lowercase: "lowercase",
  $charAt: "char_at",
  $isReal: "is_real",
  $isInt: "is_integer",
  $isBool: "is_logic",
  $castReal: "to_real",
  $castInt: "to_integer",
  $castBool: "to_logic",
  $castString: "to_string",
  $castChar: "to_char",
  $sin: "sin",
  $cos: "cos",
  $tan: "tan",
  $sqrt: "sqrt",
  $pow: "pow",
  $log: "log",
  $abs: "abs",
  $negate: "negate",
  $invert: "invert",
  $max: "maximum",
  $min: "minimum",
  $rand: "random"

}